//
// ClientStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientStatusResponse: Codable, JSONEncodable, Hashable {

    public var service: String
    public var lastGeneratedAt: Date
    public var checksum: String
    public var status: String
    public var error: String?

    public init(service: String, lastGeneratedAt: Date, checksum: String, status: String, error: String? = nil) {
        self.service = service
        self.lastGeneratedAt = lastGeneratedAt
        self.checksum = checksum
        self.status = status
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case service
        case lastGeneratedAt = "last_generated_at"
        case checksum
        case status
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(service, forKey: .service)
        try container.encode(lastGeneratedAt, forKey: .lastGeneratedAt)
        try container.encode(checksum, forKey: .checksum)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

