//
// ConfigDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConfigDetail: Codable, JSONEncodable, Hashable {

    public var env: [String: String]
    public var ports: [String: Int]

    public init(env: [String: String], ports: [String: Int]) {
        self.env = env
        self.ports = ports
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case env
        case ports
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(env, forKey: .env)
        try container.encode(ports, forKey: .ports)
    }
}

