//
// DeployRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeployRequest: Codable, JSONEncodable, Hashable {

    public var services: [String]

    public init(services: [String]) {
        self.services = services
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case services
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(services, forKey: .services)
    }
}

