//
// HealthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthResponse: Codable, JSONEncodable, Hashable {

    public var status: String
    public var uptime: String

    public init(status: String, uptime: String) {
        self.status = status
        self.uptime = uptime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case uptime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(uptime, forKey: .uptime)
    }
}

