//
// ServiceSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceSpec: Codable, JSONEncodable, Hashable {

    public var image: String
    public var ports: [String: Int]?
    public var secrets: [String]?
    public var configs: [ConfigReference]?

    public init(image: String, ports: [String: Int]? = nil, secrets: [String]? = nil, configs: [ConfigReference]? = nil) {
        self.image = image
        self.ports = ports
        self.secrets = secrets
        self.configs = configs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case ports
        case secrets
        case configs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encodeIfPresent(ports, forKey: .ports)
        try container.encodeIfPresent(secrets, forKey: .secrets)
        try container.encodeIfPresent(configs, forKey: .configs)
    }
}

