//
// ServiceDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceDetail: Codable, JSONEncodable, Hashable {

    public var name: String
    public var status: String
    public var ports: [String: Int]
    public var secrets: [String]
    public var configs: [ConfigReference]

    public init(name: String, status: String, ports: [String: Int], secrets: [String], configs: [ConfigReference]) {
        self.name = name
        self.status = status
        self.ports = ports
        self.secrets = secrets
        self.configs = configs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case status
        case ports
        case secrets
        case configs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(status, forKey: .status)
        try container.encode(ports, forKey: .ports)
        try container.encode(secrets, forKey: .secrets)
        try container.encode(configs, forKey: .configs)
    }
}

