//
// ServiceListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceListResponse: Codable, JSONEncodable, Hashable {

    public var services: [ServiceDetail]
    public var total: Int
    public var limit: Int
    public var offset: Int

    public init(services: [ServiceDetail], total: Int, limit: Int, offset: Int) {
        self.services = services
        self.total = total
        self.limit = limit
        self.offset = offset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case services
        case total
        case limit
        case offset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(services, forKey: .services)
        try container.encode(total, forKey: .total)
        try container.encode(limit, forKey: .limit)
        try container.encode(offset, forKey: .offset)
    }
}

